### PR TITLE
API Updates - navigation and engine display

### LINKED ISSUE #54: API - namespace tree
Expand the tree on the left hand menu bar to include more levels.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #54 

Major improvements to navigation on the Left Hand Sidebar, using the tree generation method.

Also updates the navigation around the engine side of the API in line with the oM side. Improves some handling of generics on the engine side as well.

On the whole, improves usability and functionality of the API documentation.

### CODE REVIEW

**Review by peterjamesnugent — COMMENTED** [review]
The side bar navigation is great! Really easy to find what you're looking for rather than scrolling.

If I click on the `BH.Engine.Structure` namespace it tells me there are no methods associated with it, when in reality it has `Compute`, `Query` etc.:
image

When I do the same on the `oM` side, it lists all the objects from `BH.oM.Structure` and the sub namespaces:
image

I think for the `Engine` we should list all the methods of those sub-namespaces to avoid any confusion - "there are no methods associated with `BH.Engine.Structure` is a bit misleading.

**Comment by FraserGreenroyd** [comment]
Thanks @peterjamesnugent - have pushed an update, lemme know what you think :smile: you might need to clear your cache to see it, just a heads up.

**Review by peterjamesnugent — COMMENTED** [review]
Works well for me.

I think it works well that clicking on a namespace doesn't expand the sub-namespaces below. 

I have noticed that the first time you click on a namespace, it kicks you back to the top level on the navigation bar - but subsequent repeats maintain the side bar:
APINavigation

Happy to approve if you think it's outside the scope of this PR and want to raise a separate issue.

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent I've fixed that for you as well - take another look, clear the cache etc. and lemme know :smile:

**Review by peterjamesnugent — APPROVED** [review]
LGTM tested on Chrome and Edge.

**Pull request merged**
